source "./committor.tcl"
NC_init "./network_params.tcl"
set qlist [list 0 3e-5 3e-4 3e-3 3e-2 0.1 0.3 0.5 0.7 0.9 0.98 0.995 1.0]
set qthis 3
set qlen [llength $qlist]
set qtarg [lindex $qlist $qthis]
if {$qthis == 0} {
    set qleft -1
    set qright [expr {$qthis + 1}]
} elseif {$qthis == [expr {$qlen - 1}]} {
    set qleft [expr {$qthis - 1}]
    set qright -2
} else {
    set qleft [expr {$qthis - 1}]
    set qright [expr {$qthis + 1}]
}

proc calcforces {} {
    global qlist qthis qlen qtarg qleft qright reactant_center product_center

    set t [getstep]
    if {$t>0} { 
        
        set cov_sum_h [cv colvar dist_hbond value]

        set cov_pair_1_2_N_N [cv colvar pair_1_2_N_N value]
		set cov_pair_1_2_N_CA [cv colvar pair_1_2_N_CA value]
		set cov_pair_1_2_N_O [cv colvar pair_1_2_N_O value]
		set cov_pair_1_2_CA_N [cv colvar pair_1_2_CA_N value]
		set cov_pair_1_2_CA_CA [cv colvar pair_1_2_CA_CA value]
		set cov_pair_1_2_CA_O [cv colvar pair_1_2_CA_O value]
		set cov_pair_1_2_O_N [cv colvar pair_1_2_O_N value]
		set cov_pair_1_2_O_CA [cv colvar pair_1_2_O_CA value]
		set cov_pair_1_2_O_O [cv colvar pair_1_2_O_O value]
		set cov_pair_1_3_N_N [cv colvar pair_1_3_N_N value]
		set cov_pair_1_3_N_CA [cv colvar pair_1_3_N_CA value]
		set cov_pair_1_3_N_O [cv colvar pair_1_3_N_O value]
		set cov_pair_1_3_CA_N [cv colvar pair_1_3_CA_N value]
		set cov_pair_1_3_CA_CA [cv colvar pair_1_3_CA_CA value]
		set cov_pair_1_3_CA_O [cv colvar pair_1_3_CA_O value]
		set cov_pair_1_3_O_N [cv colvar pair_1_3_O_N value]
		set cov_pair_1_3_O_CA [cv colvar pair_1_3_O_CA value]
		set cov_pair_1_3_O_O [cv colvar pair_1_3_O_O value]
		set cov_pair_1_4_N_N [cv colvar pair_1_4_N_N value]
		set cov_pair_1_4_N_CA [cv colvar pair_1_4_N_CA value]
		set cov_pair_1_4_N_O [cv colvar pair_1_4_N_O value]
		set cov_pair_1_4_CA_N [cv colvar pair_1_4_CA_N value]
		set cov_pair_1_4_CA_CA [cv colvar pair_1_4_CA_CA value]
		set cov_pair_1_4_CA_O [cv colvar pair_1_4_CA_O value]
		set cov_pair_1_4_O_N [cv colvar pair_1_4_O_N value]
		set cov_pair_1_4_O_CA [cv colvar pair_1_4_O_CA value]
		set cov_pair_1_4_O_O [cv colvar pair_1_4_O_O value]
		set cov_pair_1_5_N_N [cv colvar pair_1_5_N_N value]
		set cov_pair_1_5_N_CA [cv colvar pair_1_5_N_CA value]
		set cov_pair_1_5_N_O [cv colvar pair_1_5_N_O value]
		set cov_pair_1_5_CA_N [cv colvar pair_1_5_CA_N value]
		set cov_pair_1_5_CA_CA [cv colvar pair_1_5_CA_CA value]
		set cov_pair_1_5_CA_O [cv colvar pair_1_5_CA_O value]
		set cov_pair_1_5_O_N [cv colvar pair_1_5_O_N value]
		set cov_pair_1_5_O_CA [cv colvar pair_1_5_O_CA value]
		set cov_pair_1_5_O_O [cv colvar pair_1_5_O_O value]
		set cov_pair_1_6_N_N [cv colvar pair_1_6_N_N value]
		set cov_pair_1_6_N_CA [cv colvar pair_1_6_N_CA value]
		set cov_pair_1_6_N_O [cv colvar pair_1_6_N_O value]
		set cov_pair_1_6_CA_N [cv colvar pair_1_6_CA_N value]
		set cov_pair_1_6_CA_CA [cv colvar pair_1_6_CA_CA value]
		set cov_pair_1_6_CA_O [cv colvar pair_1_6_CA_O value]
		set cov_pair_1_6_O_N [cv colvar pair_1_6_O_N value]
		set cov_pair_1_6_O_CA [cv colvar pair_1_6_O_CA value]
		set cov_pair_1_6_O_O [cv colvar pair_1_6_O_O value]
		set cov_pair_1_7_N_N [cv colvar pair_1_7_N_N value]
		set cov_pair_1_7_N_CA [cv colvar pair_1_7_N_CA value]
		set cov_pair_1_7_N_O [cv colvar pair_1_7_N_O value]
		set cov_pair_1_7_CA_N [cv colvar pair_1_7_CA_N value]
		set cov_pair_1_7_CA_CA [cv colvar pair_1_7_CA_CA value]
		set cov_pair_1_7_CA_O [cv colvar pair_1_7_CA_O value]
		set cov_pair_1_7_O_N [cv colvar pair_1_7_O_N value]
		set cov_pair_1_7_O_CA [cv colvar pair_1_7_O_CA value]
		set cov_pair_1_7_O_O [cv colvar pair_1_7_O_O value]
		set cov_pair_1_8_N_N [cv colvar pair_1_8_N_N value]
		set cov_pair_1_8_N_CA [cv colvar pair_1_8_N_CA value]
		set cov_pair_1_8_N_O [cv colvar pair_1_8_N_O value]
		set cov_pair_1_8_CA_N [cv colvar pair_1_8_CA_N value]
		set cov_pair_1_8_CA_CA [cv colvar pair_1_8_CA_CA value]
		set cov_pair_1_8_CA_O [cv colvar pair_1_8_CA_O value]
		set cov_pair_1_8_O_N [cv colvar pair_1_8_O_N value]
		set cov_pair_1_8_O_CA [cv colvar pair_1_8_O_CA value]
		set cov_pair_1_8_O_O [cv colvar pair_1_8_O_O value]
		set cov_pair_1_9_N_N [cv colvar pair_1_9_N_N value]
		set cov_pair_1_9_N_CA [cv colvar pair_1_9_N_CA value]
		set cov_pair_1_9_N_O [cv colvar pair_1_9_N_O value]
		set cov_pair_1_9_CA_N [cv colvar pair_1_9_CA_N value]
		set cov_pair_1_9_CA_CA [cv colvar pair_1_9_CA_CA value]
		set cov_pair_1_9_CA_O [cv colvar pair_1_9_CA_O value]
		set cov_pair_1_9_O_N [cv colvar pair_1_9_O_N value]
		set cov_pair_1_9_O_CA [cv colvar pair_1_9_O_CA value]
		set cov_pair_1_9_O_O [cv colvar pair_1_9_O_O value]
		set cov_pair_1_10_N_N [cv colvar pair_1_10_N_N value]
		set cov_pair_1_10_N_CA [cv colvar pair_1_10_N_CA value]
		set cov_pair_1_10_N_O [cv colvar pair_1_10_N_O value]
		set cov_pair_1_10_CA_N [cv colvar pair_1_10_CA_N value]
		set cov_pair_1_10_CA_CA [cv colvar pair_1_10_CA_CA value]
		set cov_pair_1_10_CA_O [cv colvar pair_1_10_CA_O value]
		set cov_pair_1_10_O_N [cv colvar pair_1_10_O_N value]
		set cov_pair_1_10_O_CA [cv colvar pair_1_10_O_CA value]
		set cov_pair_1_10_O_O [cv colvar pair_1_10_O_O value]
		set cov_pair_2_3_N_N [cv colvar pair_2_3_N_N value]
		set cov_pair_2_3_N_CA [cv colvar pair_2_3_N_CA value]
		set cov_pair_2_3_N_O [cv colvar pair_2_3_N_O value]
		set cov_pair_2_3_CA_N [cv colvar pair_2_3_CA_N value]
		set cov_pair_2_3_CA_CA [cv colvar pair_2_3_CA_CA value]
		set cov_pair_2_3_CA_O [cv colvar pair_2_3_CA_O value]
		set cov_pair_2_3_O_N [cv colvar pair_2_3_O_N value]
		set cov_pair_2_3_O_CA [cv colvar pair_2_3_O_CA value]
		set cov_pair_2_3_O_O [cv colvar pair_2_3_O_O value]
		set cov_pair_2_4_N_N [cv colvar pair_2_4_N_N value]
		set cov_pair_2_4_N_CA [cv colvar pair_2_4_N_CA value]
		set cov_pair_2_4_N_O [cv colvar pair_2_4_N_O value]
		set cov_pair_2_4_CA_N [cv colvar pair_2_4_CA_N value]
		set cov_pair_2_4_CA_CA [cv colvar pair_2_4_CA_CA value]
		set cov_pair_2_4_CA_O [cv colvar pair_2_4_CA_O value]
		set cov_pair_2_4_O_N [cv colvar pair_2_4_O_N value]
		set cov_pair_2_4_O_CA [cv colvar pair_2_4_O_CA value]
		set cov_pair_2_4_O_O [cv colvar pair_2_4_O_O value]
		set cov_pair_2_5_N_N [cv colvar pair_2_5_N_N value]
		set cov_pair_2_5_N_CA [cv colvar pair_2_5_N_CA value]
		set cov_pair_2_5_N_O [cv colvar pair_2_5_N_O value]
		set cov_pair_2_5_CA_N [cv colvar pair_2_5_CA_N value]
		set cov_pair_2_5_CA_CA [cv colvar pair_2_5_CA_CA value]
		set cov_pair_2_5_CA_O [cv colvar pair_2_5_CA_O value]
		set cov_pair_2_5_O_N [cv colvar pair_2_5_O_N value]
		set cov_pair_2_5_O_CA [cv colvar pair_2_5_O_CA value]
		set cov_pair_2_5_O_O [cv colvar pair_2_5_O_O value]
		set cov_pair_2_6_N_N [cv colvar pair_2_6_N_N value]
		set cov_pair_2_6_N_CA [cv colvar pair_2_6_N_CA value]
		set cov_pair_2_6_N_O [cv colvar pair_2_6_N_O value]
		set cov_pair_2_6_CA_N [cv colvar pair_2_6_CA_N value]
		set cov_pair_2_6_CA_CA [cv colvar pair_2_6_CA_CA value]
		set cov_pair_2_6_CA_O [cv colvar pair_2_6_CA_O value]
		set cov_pair_2_6_O_N [cv colvar pair_2_6_O_N value]
		set cov_pair_2_6_O_CA [cv colvar pair_2_6_O_CA value]
		set cov_pair_2_6_O_O [cv colvar pair_2_6_O_O value]
		set cov_pair_2_7_N_N [cv colvar pair_2_7_N_N value]
		set cov_pair_2_7_N_CA [cv colvar pair_2_7_N_CA value]
		set cov_pair_2_7_N_O [cv colvar pair_2_7_N_O value]
		set cov_pair_2_7_CA_N [cv colvar pair_2_7_CA_N value]
		set cov_pair_2_7_CA_CA [cv colvar pair_2_7_CA_CA value]
		set cov_pair_2_7_CA_O [cv colvar pair_2_7_CA_O value]
		set cov_pair_2_7_O_N [cv colvar pair_2_7_O_N value]
		set cov_pair_2_7_O_CA [cv colvar pair_2_7_O_CA value]
		set cov_pair_2_7_O_O [cv colvar pair_2_7_O_O value]
		set cov_pair_2_8_N_N [cv colvar pair_2_8_N_N value]
		set cov_pair_2_8_N_CA [cv colvar pair_2_8_N_CA value]
		set cov_pair_2_8_N_O [cv colvar pair_2_8_N_O value]
		set cov_pair_2_8_CA_N [cv colvar pair_2_8_CA_N value]
		set cov_pair_2_8_CA_CA [cv colvar pair_2_8_CA_CA value]
		set cov_pair_2_8_CA_O [cv colvar pair_2_8_CA_O value]
		set cov_pair_2_8_O_N [cv colvar pair_2_8_O_N value]
		set cov_pair_2_8_O_CA [cv colvar pair_2_8_O_CA value]
		set cov_pair_2_8_O_O [cv colvar pair_2_8_O_O value]
		set cov_pair_2_9_N_N [cv colvar pair_2_9_N_N value]
		set cov_pair_2_9_N_CA [cv colvar pair_2_9_N_CA value]
		set cov_pair_2_9_N_O [cv colvar pair_2_9_N_O value]
		set cov_pair_2_9_CA_N [cv colvar pair_2_9_CA_N value]
		set cov_pair_2_9_CA_CA [cv colvar pair_2_9_CA_CA value]
		set cov_pair_2_9_CA_O [cv colvar pair_2_9_CA_O value]
		set cov_pair_2_9_O_N [cv colvar pair_2_9_O_N value]
		set cov_pair_2_9_O_CA [cv colvar pair_2_9_O_CA value]
		set cov_pair_2_9_O_O [cv colvar pair_2_9_O_O value]
		set cov_pair_2_10_N_N [cv colvar pair_2_10_N_N value]
		set cov_pair_2_10_N_CA [cv colvar pair_2_10_N_CA value]
		set cov_pair_2_10_N_O [cv colvar pair_2_10_N_O value]
		set cov_pair_2_10_CA_N [cv colvar pair_2_10_CA_N value]
		set cov_pair_2_10_CA_CA [cv colvar pair_2_10_CA_CA value]
		set cov_pair_2_10_CA_O [cv colvar pair_2_10_CA_O value]
		set cov_pair_2_10_O_N [cv colvar pair_2_10_O_N value]
		set cov_pair_2_10_O_CA [cv colvar pair_2_10_O_CA value]
		set cov_pair_2_10_O_O [cv colvar pair_2_10_O_O value]
		set cov_pair_3_4_N_N [cv colvar pair_3_4_N_N value]
		set cov_pair_3_4_N_CA [cv colvar pair_3_4_N_CA value]
		set cov_pair_3_4_N_O [cv colvar pair_3_4_N_O value]
		set cov_pair_3_4_CA_N [cv colvar pair_3_4_CA_N value]
		set cov_pair_3_4_CA_CA [cv colvar pair_3_4_CA_CA value]
		set cov_pair_3_4_CA_O [cv colvar pair_3_4_CA_O value]
		set cov_pair_3_4_O_N [cv colvar pair_3_4_O_N value]
		set cov_pair_3_4_O_CA [cv colvar pair_3_4_O_CA value]
		set cov_pair_3_4_O_O [cv colvar pair_3_4_O_O value]
		set cov_pair_3_5_N_N [cv colvar pair_3_5_N_N value]
		set cov_pair_3_5_N_CA [cv colvar pair_3_5_N_CA value]
		set cov_pair_3_5_N_O [cv colvar pair_3_5_N_O value]
		set cov_pair_3_5_CA_N [cv colvar pair_3_5_CA_N value]
		set cov_pair_3_5_CA_CA [cv colvar pair_3_5_CA_CA value]
		set cov_pair_3_5_CA_O [cv colvar pair_3_5_CA_O value]
		set cov_pair_3_5_O_N [cv colvar pair_3_5_O_N value]
		set cov_pair_3_5_O_CA [cv colvar pair_3_5_O_CA value]
		set cov_pair_3_5_O_O [cv colvar pair_3_5_O_O value]
		set cov_pair_3_6_N_N [cv colvar pair_3_6_N_N value]
		set cov_pair_3_6_N_CA [cv colvar pair_3_6_N_CA value]
		set cov_pair_3_6_N_O [cv colvar pair_3_6_N_O value]
		set cov_pair_3_6_CA_N [cv colvar pair_3_6_CA_N value]
		set cov_pair_3_6_CA_CA [cv colvar pair_3_6_CA_CA value]
		set cov_pair_3_6_CA_O [cv colvar pair_3_6_CA_O value]
		set cov_pair_3_6_O_N [cv colvar pair_3_6_O_N value]
		set cov_pair_3_6_O_CA [cv colvar pair_3_6_O_CA value]
		set cov_pair_3_6_O_O [cv colvar pair_3_6_O_O value]
		set cov_pair_3_7_N_N [cv colvar pair_3_7_N_N value]
		set cov_pair_3_7_N_CA [cv colvar pair_3_7_N_CA value]
		set cov_pair_3_7_N_O [cv colvar pair_3_7_N_O value]
		set cov_pair_3_7_CA_N [cv colvar pair_3_7_CA_N value]
		set cov_pair_3_7_CA_CA [cv colvar pair_3_7_CA_CA value]
		set cov_pair_3_7_CA_O [cv colvar pair_3_7_CA_O value]
		set cov_pair_3_7_O_N [cv colvar pair_3_7_O_N value]
		set cov_pair_3_7_O_CA [cv colvar pair_3_7_O_CA value]
		set cov_pair_3_7_O_O [cv colvar pair_3_7_O_O value]
		set cov_pair_3_8_N_N [cv colvar pair_3_8_N_N value]
		set cov_pair_3_8_N_CA [cv colvar pair_3_8_N_CA value]
		set cov_pair_3_8_N_O [cv colvar pair_3_8_N_O value]
		set cov_pair_3_8_CA_N [cv colvar pair_3_8_CA_N value]
		set cov_pair_3_8_CA_CA [cv colvar pair_3_8_CA_CA value]
		set cov_pair_3_8_CA_O [cv colvar pair_3_8_CA_O value]
		set cov_pair_3_8_O_N [cv colvar pair_3_8_O_N value]
		set cov_pair_3_8_O_CA [cv colvar pair_3_8_O_CA value]
		set cov_pair_3_8_O_O [cv colvar pair_3_8_O_O value]
		set cov_pair_3_9_N_N [cv colvar pair_3_9_N_N value]
		set cov_pair_3_9_N_CA [cv colvar pair_3_9_N_CA value]
		set cov_pair_3_9_N_O [cv colvar pair_3_9_N_O value]
		set cov_pair_3_9_CA_N [cv colvar pair_3_9_CA_N value]
		set cov_pair_3_9_CA_CA [cv colvar pair_3_9_CA_CA value]
		set cov_pair_3_9_CA_O [cv colvar pair_3_9_CA_O value]
		set cov_pair_3_9_O_N [cv colvar pair_3_9_O_N value]
		set cov_pair_3_9_O_CA [cv colvar pair_3_9_O_CA value]
		set cov_pair_3_9_O_O [cv colvar pair_3_9_O_O value]
		set cov_pair_3_10_N_N [cv colvar pair_3_10_N_N value]
		set cov_pair_3_10_N_CA [cv colvar pair_3_10_N_CA value]
		set cov_pair_3_10_N_O [cv colvar pair_3_10_N_O value]
		set cov_pair_3_10_CA_N [cv colvar pair_3_10_CA_N value]
		set cov_pair_3_10_CA_CA [cv colvar pair_3_10_CA_CA value]
		set cov_pair_3_10_CA_O [cv colvar pair_3_10_CA_O value]
		set cov_pair_3_10_O_N [cv colvar pair_3_10_O_N value]
		set cov_pair_3_10_O_CA [cv colvar pair_3_10_O_CA value]
		set cov_pair_3_10_O_O [cv colvar pair_3_10_O_O value]
		set cov_pair_4_5_N_N [cv colvar pair_4_5_N_N value]
		set cov_pair_4_5_N_CA [cv colvar pair_4_5_N_CA value]
		set cov_pair_4_5_N_O [cv colvar pair_4_5_N_O value]
		set cov_pair_4_5_CA_N [cv colvar pair_4_5_CA_N value]
		set cov_pair_4_5_CA_CA [cv colvar pair_4_5_CA_CA value]
		set cov_pair_4_5_CA_O [cv colvar pair_4_5_CA_O value]
		set cov_pair_4_5_O_N [cv colvar pair_4_5_O_N value]
		set cov_pair_4_5_O_CA [cv colvar pair_4_5_O_CA value]
		set cov_pair_4_5_O_O [cv colvar pair_4_5_O_O value]
		set cov_pair_4_6_N_N [cv colvar pair_4_6_N_N value]
		set cov_pair_4_6_N_CA [cv colvar pair_4_6_N_CA value]
		set cov_pair_4_6_N_O [cv colvar pair_4_6_N_O value]
		set cov_pair_4_6_CA_N [cv colvar pair_4_6_CA_N value]
		set cov_pair_4_6_CA_CA [cv colvar pair_4_6_CA_CA value]
		set cov_pair_4_6_CA_O [cv colvar pair_4_6_CA_O value]
		set cov_pair_4_6_O_N [cv colvar pair_4_6_O_N value]
		set cov_pair_4_6_O_CA [cv colvar pair_4_6_O_CA value]
		set cov_pair_4_6_O_O [cv colvar pair_4_6_O_O value]
		set cov_pair_4_7_N_N [cv colvar pair_4_7_N_N value]
		set cov_pair_4_7_N_CA [cv colvar pair_4_7_N_CA value]
		set cov_pair_4_7_N_O [cv colvar pair_4_7_N_O value]
		set cov_pair_4_7_CA_N [cv colvar pair_4_7_CA_N value]
		set cov_pair_4_7_CA_CA [cv colvar pair_4_7_CA_CA value]
		set cov_pair_4_7_CA_O [cv colvar pair_4_7_CA_O value]
		set cov_pair_4_7_O_N [cv colvar pair_4_7_O_N value]
		set cov_pair_4_7_O_CA [cv colvar pair_4_7_O_CA value]
		set cov_pair_4_7_O_O [cv colvar pair_4_7_O_O value]
		set cov_pair_4_8_N_N [cv colvar pair_4_8_N_N value]
		set cov_pair_4_8_N_CA [cv colvar pair_4_8_N_CA value]
		set cov_pair_4_8_N_O [cv colvar pair_4_8_N_O value]
		set cov_pair_4_8_CA_N [cv colvar pair_4_8_CA_N value]
		set cov_pair_4_8_CA_CA [cv colvar pair_4_8_CA_CA value]
		set cov_pair_4_8_CA_O [cv colvar pair_4_8_CA_O value]
		set cov_pair_4_8_O_N [cv colvar pair_4_8_O_N value]
		set cov_pair_4_8_O_CA [cv colvar pair_4_8_O_CA value]
		set cov_pair_4_8_O_O [cv colvar pair_4_8_O_O value]
		set cov_pair_4_9_N_N [cv colvar pair_4_9_N_N value]
		set cov_pair_4_9_N_CA [cv colvar pair_4_9_N_CA value]
		set cov_pair_4_9_N_O [cv colvar pair_4_9_N_O value]
		set cov_pair_4_9_CA_N [cv colvar pair_4_9_CA_N value]
		set cov_pair_4_9_CA_CA [cv colvar pair_4_9_CA_CA value]
		set cov_pair_4_9_CA_O [cv colvar pair_4_9_CA_O value]
		set cov_pair_4_9_O_N [cv colvar pair_4_9_O_N value]
		set cov_pair_4_9_O_CA [cv colvar pair_4_9_O_CA value]
		set cov_pair_4_9_O_O [cv colvar pair_4_9_O_O value]
		set cov_pair_4_10_N_N [cv colvar pair_4_10_N_N value]
		set cov_pair_4_10_N_CA [cv colvar pair_4_10_N_CA value]
		set cov_pair_4_10_N_O [cv colvar pair_4_10_N_O value]
		set cov_pair_4_10_CA_N [cv colvar pair_4_10_CA_N value]
		set cov_pair_4_10_CA_CA [cv colvar pair_4_10_CA_CA value]
		set cov_pair_4_10_CA_O [cv colvar pair_4_10_CA_O value]
		set cov_pair_4_10_O_N [cv colvar pair_4_10_O_N value]
		set cov_pair_4_10_O_CA [cv colvar pair_4_10_O_CA value]
		set cov_pair_4_10_O_O [cv colvar pair_4_10_O_O value]
		set cov_pair_5_6_N_N [cv colvar pair_5_6_N_N value]
		set cov_pair_5_6_N_CA [cv colvar pair_5_6_N_CA value]
		set cov_pair_5_6_N_O [cv colvar pair_5_6_N_O value]
		set cov_pair_5_6_CA_N [cv colvar pair_5_6_CA_N value]
		set cov_pair_5_6_CA_CA [cv colvar pair_5_6_CA_CA value]
		set cov_pair_5_6_CA_O [cv colvar pair_5_6_CA_O value]
		set cov_pair_5_6_O_N [cv colvar pair_5_6_O_N value]
		set cov_pair_5_6_O_CA [cv colvar pair_5_6_O_CA value]
		set cov_pair_5_6_O_O [cv colvar pair_5_6_O_O value]
		set cov_pair_5_7_N_N [cv colvar pair_5_7_N_N value]
		set cov_pair_5_7_N_CA [cv colvar pair_5_7_N_CA value]
		set cov_pair_5_7_N_O [cv colvar pair_5_7_N_O value]
		set cov_pair_5_7_CA_N [cv colvar pair_5_7_CA_N value]
		set cov_pair_5_7_CA_CA [cv colvar pair_5_7_CA_CA value]
		set cov_pair_5_7_CA_O [cv colvar pair_5_7_CA_O value]
		set cov_pair_5_7_O_N [cv colvar pair_5_7_O_N value]
		set cov_pair_5_7_O_CA [cv colvar pair_5_7_O_CA value]
		set cov_pair_5_7_O_O [cv colvar pair_5_7_O_O value]
		set cov_pair_5_8_N_N [cv colvar pair_5_8_N_N value]
		set cov_pair_5_8_N_CA [cv colvar pair_5_8_N_CA value]
		set cov_pair_5_8_N_O [cv colvar pair_5_8_N_O value]
		set cov_pair_5_8_CA_N [cv colvar pair_5_8_CA_N value]
		set cov_pair_5_8_CA_CA [cv colvar pair_5_8_CA_CA value]
		set cov_pair_5_8_CA_O [cv colvar pair_5_8_CA_O value]
		set cov_pair_5_8_O_N [cv colvar pair_5_8_O_N value]
		set cov_pair_5_8_O_CA [cv colvar pair_5_8_O_CA value]
		set cov_pair_5_8_O_O [cv colvar pair_5_8_O_O value]
		set cov_pair_5_9_N_N [cv colvar pair_5_9_N_N value]
		set cov_pair_5_9_N_CA [cv colvar pair_5_9_N_CA value]
		set cov_pair_5_9_N_O [cv colvar pair_5_9_N_O value]
		set cov_pair_5_9_CA_N [cv colvar pair_5_9_CA_N value]
		set cov_pair_5_9_CA_CA [cv colvar pair_5_9_CA_CA value]
		set cov_pair_5_9_CA_O [cv colvar pair_5_9_CA_O value]
		set cov_pair_5_9_O_N [cv colvar pair_5_9_O_N value]
		set cov_pair_5_9_O_CA [cv colvar pair_5_9_O_CA value]
		set cov_pair_5_9_O_O [cv colvar pair_5_9_O_O value]
		set cov_pair_5_10_N_N [cv colvar pair_5_10_N_N value]
		set cov_pair_5_10_N_CA [cv colvar pair_5_10_N_CA value]
		set cov_pair_5_10_N_O [cv colvar pair_5_10_N_O value]
		set cov_pair_5_10_CA_N [cv colvar pair_5_10_CA_N value]
		set cov_pair_5_10_CA_CA [cv colvar pair_5_10_CA_CA value]
		set cov_pair_5_10_CA_O [cv colvar pair_5_10_CA_O value]
		set cov_pair_5_10_O_N [cv colvar pair_5_10_O_N value]
		set cov_pair_5_10_O_CA [cv colvar pair_5_10_O_CA value]
		set cov_pair_5_10_O_O [cv colvar pair_5_10_O_O value]
		set cov_pair_6_7_N_N [cv colvar pair_6_7_N_N value]
		set cov_pair_6_7_N_CA [cv colvar pair_6_7_N_CA value]
		set cov_pair_6_7_N_O [cv colvar pair_6_7_N_O value]
		set cov_pair_6_7_CA_N [cv colvar pair_6_7_CA_N value]
		set cov_pair_6_7_CA_CA [cv colvar pair_6_7_CA_CA value]
		set cov_pair_6_7_CA_O [cv colvar pair_6_7_CA_O value]
		set cov_pair_6_7_O_N [cv colvar pair_6_7_O_N value]
		set cov_pair_6_7_O_CA [cv colvar pair_6_7_O_CA value]
		set cov_pair_6_7_O_O [cv colvar pair_6_7_O_O value]
		set cov_pair_6_8_N_N [cv colvar pair_6_8_N_N value]
		set cov_pair_6_8_N_CA [cv colvar pair_6_8_N_CA value]
		set cov_pair_6_8_N_O [cv colvar pair_6_8_N_O value]
		set cov_pair_6_8_CA_N [cv colvar pair_6_8_CA_N value]
		set cov_pair_6_8_CA_CA [cv colvar pair_6_8_CA_CA value]
		set cov_pair_6_8_CA_O [cv colvar pair_6_8_CA_O value]
		set cov_pair_6_8_O_N [cv colvar pair_6_8_O_N value]
		set cov_pair_6_8_O_CA [cv colvar pair_6_8_O_CA value]
		set cov_pair_6_8_O_O [cv colvar pair_6_8_O_O value]
		set cov_pair_6_9_N_N [cv colvar pair_6_9_N_N value]
		set cov_pair_6_9_N_CA [cv colvar pair_6_9_N_CA value]
		set cov_pair_6_9_N_O [cv colvar pair_6_9_N_O value]
		set cov_pair_6_9_CA_N [cv colvar pair_6_9_CA_N value]
		set cov_pair_6_9_CA_CA [cv colvar pair_6_9_CA_CA value]
		set cov_pair_6_9_CA_O [cv colvar pair_6_9_CA_O value]
		set cov_pair_6_9_O_N [cv colvar pair_6_9_O_N value]
		set cov_pair_6_9_O_CA [cv colvar pair_6_9_O_CA value]
		set cov_pair_6_9_O_O [cv colvar pair_6_9_O_O value]
		set cov_pair_6_10_N_N [cv colvar pair_6_10_N_N value]
		set cov_pair_6_10_N_CA [cv colvar pair_6_10_N_CA value]
		set cov_pair_6_10_N_O [cv colvar pair_6_10_N_O value]
		set cov_pair_6_10_CA_N [cv colvar pair_6_10_CA_N value]
		set cov_pair_6_10_CA_CA [cv colvar pair_6_10_CA_CA value]
		set cov_pair_6_10_CA_O [cv colvar pair_6_10_CA_O value]
		set cov_pair_6_10_O_N [cv colvar pair_6_10_O_N value]
		set cov_pair_6_10_O_CA [cv colvar pair_6_10_O_CA value]
		set cov_pair_6_10_O_O [cv colvar pair_6_10_O_O value]
		set cov_pair_7_8_N_N [cv colvar pair_7_8_N_N value]
		set cov_pair_7_8_N_CA [cv colvar pair_7_8_N_CA value]
		set cov_pair_7_8_N_O [cv colvar pair_7_8_N_O value]
		set cov_pair_7_8_CA_N [cv colvar pair_7_8_CA_N value]
		set cov_pair_7_8_CA_CA [cv colvar pair_7_8_CA_CA value]
		set cov_pair_7_8_CA_O [cv colvar pair_7_8_CA_O value]
		set cov_pair_7_8_O_N [cv colvar pair_7_8_O_N value]
		set cov_pair_7_8_O_CA [cv colvar pair_7_8_O_CA value]
		set cov_pair_7_8_O_O [cv colvar pair_7_8_O_O value]
		set cov_pair_7_9_N_N [cv colvar pair_7_9_N_N value]
		set cov_pair_7_9_N_CA [cv colvar pair_7_9_N_CA value]
		set cov_pair_7_9_N_O [cv colvar pair_7_9_N_O value]
		set cov_pair_7_9_CA_N [cv colvar pair_7_9_CA_N value]
		set cov_pair_7_9_CA_CA [cv colvar pair_7_9_CA_CA value]
		set cov_pair_7_9_CA_O [cv colvar pair_7_9_CA_O value]
		set cov_pair_7_9_O_N [cv colvar pair_7_9_O_N value]
		set cov_pair_7_9_O_CA [cv colvar pair_7_9_O_CA value]
		set cov_pair_7_9_O_O [cv colvar pair_7_9_O_O value]
		set cov_pair_7_10_N_N [cv colvar pair_7_10_N_N value]
		set cov_pair_7_10_N_CA [cv colvar pair_7_10_N_CA value]
		set cov_pair_7_10_N_O [cv colvar pair_7_10_N_O value]
		set cov_pair_7_10_CA_N [cv colvar pair_7_10_CA_N value]
		set cov_pair_7_10_CA_CA [cv colvar pair_7_10_CA_CA value]
		set cov_pair_7_10_CA_O [cv colvar pair_7_10_CA_O value]
		set cov_pair_7_10_O_N [cv colvar pair_7_10_O_N value]
		set cov_pair_7_10_O_CA [cv colvar pair_7_10_O_CA value]
		set cov_pair_7_10_O_O [cv colvar pair_7_10_O_O value]
		set cov_pair_8_9_N_N [cv colvar pair_8_9_N_N value]
		set cov_pair_8_9_N_CA [cv colvar pair_8_9_N_CA value]
		set cov_pair_8_9_N_O [cv colvar pair_8_9_N_O value]
		set cov_pair_8_9_CA_N [cv colvar pair_8_9_CA_N value]
		set cov_pair_8_9_CA_CA [cv colvar pair_8_9_CA_CA value]
		set cov_pair_8_9_CA_O [cv colvar pair_8_9_CA_O value]
		set cov_pair_8_9_O_N [cv colvar pair_8_9_O_N value]
		set cov_pair_8_9_O_CA [cv colvar pair_8_9_O_CA value]
		set cov_pair_8_9_O_O [cv colvar pair_8_9_O_O value]
		set cov_pair_8_10_N_N [cv colvar pair_8_10_N_N value]
		set cov_pair_8_10_N_CA [cv colvar pair_8_10_N_CA value]
		set cov_pair_8_10_N_O [cv colvar pair_8_10_N_O value]
		set cov_pair_8_10_CA_N [cv colvar pair_8_10_CA_N value]
		set cov_pair_8_10_CA_CA [cv colvar pair_8_10_CA_CA value]
		set cov_pair_8_10_CA_O [cv colvar pair_8_10_CA_O value]
		set cov_pair_8_10_O_N [cv colvar pair_8_10_O_N value]
		set cov_pair_8_10_O_CA [cv colvar pair_8_10_O_CA value]
		set cov_pair_8_10_O_O [cv colvar pair_8_10_O_O value]
		set cov_pair_9_10_N_N [cv colvar pair_9_10_N_N value]
		set cov_pair_9_10_N_CA [cv colvar pair_9_10_N_CA value]
		set cov_pair_9_10_N_O [cv colvar pair_9_10_N_O value]
		set cov_pair_9_10_CA_N [cv colvar pair_9_10_CA_N value]
		set cov_pair_9_10_CA_CA [cv colvar pair_9_10_CA_CA value]
		set cov_pair_9_10_CA_O [cv colvar pair_9_10_CA_O value]
		set cov_pair_9_10_O_N [cv colvar pair_9_10_O_N value]
		set cov_pair_9_10_O_CA [cv colvar pair_9_10_O_CA value]
		set cov_pair_9_10_O_O [cv colvar pair_9_10_O_O value]
		
		set q_input [list $cov_pair_1_2_N_N $cov_pair_1_2_N_CA $cov_pair_1_2_N_O $cov_pair_1_2_CA_N $cov_pair_1_2_CA_CA $cov_pair_1_2_CA_O $cov_pair_1_2_O_N $cov_pair_1_2_O_CA $cov_pair_1_2_O_O $cov_pair_1_3_N_N $cov_pair_1_3_N_CA $cov_pair_1_3_N_O $cov_pair_1_3_CA_N $cov_pair_1_3_CA_CA $cov_pair_1_3_CA_O $cov_pair_1_3_O_N $cov_pair_1_3_O_CA $cov_pair_1_3_O_O $cov_pair_1_4_N_N $cov_pair_1_4_N_CA $cov_pair_1_4_N_O $cov_pair_1_4_CA_N $cov_pair_1_4_CA_CA $cov_pair_1_4_CA_O $cov_pair_1_4_O_N $cov_pair_1_4_O_CA $cov_pair_1_4_O_O $cov_pair_1_5_N_N $cov_pair_1_5_N_CA $cov_pair_1_5_N_O $cov_pair_1_5_CA_N $cov_pair_1_5_CA_CA $cov_pair_1_5_CA_O $cov_pair_1_5_O_N $cov_pair_1_5_O_CA $cov_pair_1_5_O_O $cov_pair_1_6_N_N $cov_pair_1_6_N_CA $cov_pair_1_6_N_O $cov_pair_1_6_CA_N $cov_pair_1_6_CA_CA $cov_pair_1_6_CA_O $cov_pair_1_6_O_N $cov_pair_1_6_O_CA $cov_pair_1_6_O_O $cov_pair_1_7_N_N $cov_pair_1_7_N_CA $cov_pair_1_7_N_O $cov_pair_1_7_CA_N $cov_pair_1_7_CA_CA $cov_pair_1_7_CA_O $cov_pair_1_7_O_N $cov_pair_1_7_O_CA $cov_pair_1_7_O_O $cov_pair_1_8_N_N $cov_pair_1_8_N_CA $cov_pair_1_8_N_O $cov_pair_1_8_CA_N $cov_pair_1_8_CA_CA $cov_pair_1_8_CA_O $cov_pair_1_8_O_N $cov_pair_1_8_O_CA $cov_pair_1_8_O_O $cov_pair_1_9_N_N $cov_pair_1_9_N_CA $cov_pair_1_9_N_O $cov_pair_1_9_CA_N $cov_pair_1_9_CA_CA $cov_pair_1_9_CA_O $cov_pair_1_9_O_N $cov_pair_1_9_O_CA $cov_pair_1_9_O_O $cov_pair_1_10_N_N $cov_pair_1_10_N_CA $cov_pair_1_10_N_O $cov_pair_1_10_CA_N $cov_pair_1_10_CA_CA $cov_pair_1_10_CA_O $cov_pair_1_10_O_N $cov_pair_1_10_O_CA $cov_pair_1_10_O_O $cov_pair_2_3_N_N $cov_pair_2_3_N_CA $cov_pair_2_3_N_O $cov_pair_2_3_CA_N $cov_pair_2_3_CA_CA $cov_pair_2_3_CA_O $cov_pair_2_3_O_N $cov_pair_2_3_O_CA $cov_pair_2_3_O_O $cov_pair_2_4_N_N $cov_pair_2_4_N_CA $cov_pair_2_4_N_O $cov_pair_2_4_CA_N $cov_pair_2_4_CA_CA $cov_pair_2_4_CA_O $cov_pair_2_4_O_N $cov_pair_2_4_O_CA $cov_pair_2_4_O_O $cov_pair_2_5_N_N $cov_pair_2_5_N_CA $cov_pair_2_5_N_O $cov_pair_2_5_CA_N $cov_pair_2_5_CA_CA $cov_pair_2_5_CA_O $cov_pair_2_5_O_N $cov_pair_2_5_O_CA $cov_pair_2_5_O_O $cov_pair_2_6_N_N $cov_pair_2_6_N_CA $cov_pair_2_6_N_O $cov_pair_2_6_CA_N $cov_pair_2_6_CA_CA $cov_pair_2_6_CA_O $cov_pair_2_6_O_N $cov_pair_2_6_O_CA $cov_pair_2_6_O_O $cov_pair_2_7_N_N $cov_pair_2_7_N_CA $cov_pair_2_7_N_O $cov_pair_2_7_CA_N $cov_pair_2_7_CA_CA $cov_pair_2_7_CA_O $cov_pair_2_7_O_N $cov_pair_2_7_O_CA $cov_pair_2_7_O_O $cov_pair_2_8_N_N $cov_pair_2_8_N_CA $cov_pair_2_8_N_O $cov_pair_2_8_CA_N $cov_pair_2_8_CA_CA $cov_pair_2_8_CA_O $cov_pair_2_8_O_N $cov_pair_2_8_O_CA $cov_pair_2_8_O_O $cov_pair_2_9_N_N $cov_pair_2_9_N_CA $cov_pair_2_9_N_O $cov_pair_2_9_CA_N $cov_pair_2_9_CA_CA $cov_pair_2_9_CA_O $cov_pair_2_9_O_N $cov_pair_2_9_O_CA $cov_pair_2_9_O_O $cov_pair_2_10_N_N $cov_pair_2_10_N_CA $cov_pair_2_10_N_O $cov_pair_2_10_CA_N $cov_pair_2_10_CA_CA $cov_pair_2_10_CA_O $cov_pair_2_10_O_N $cov_pair_2_10_O_CA $cov_pair_2_10_O_O $cov_pair_3_4_N_N $cov_pair_3_4_N_CA $cov_pair_3_4_N_O $cov_pair_3_4_CA_N $cov_pair_3_4_CA_CA $cov_pair_3_4_CA_O $cov_pair_3_4_O_N $cov_pair_3_4_O_CA $cov_pair_3_4_O_O $cov_pair_3_5_N_N $cov_pair_3_5_N_CA $cov_pair_3_5_N_O $cov_pair_3_5_CA_N $cov_pair_3_5_CA_CA $cov_pair_3_5_CA_O $cov_pair_3_5_O_N $cov_pair_3_5_O_CA $cov_pair_3_5_O_O $cov_pair_3_6_N_N $cov_pair_3_6_N_CA $cov_pair_3_6_N_O $cov_pair_3_6_CA_N $cov_pair_3_6_CA_CA $cov_pair_3_6_CA_O $cov_pair_3_6_O_N $cov_pair_3_6_O_CA $cov_pair_3_6_O_O $cov_pair_3_7_N_N $cov_pair_3_7_N_CA $cov_pair_3_7_N_O $cov_pair_3_7_CA_N $cov_pair_3_7_CA_CA $cov_pair_3_7_CA_O $cov_pair_3_7_O_N $cov_pair_3_7_O_CA $cov_pair_3_7_O_O $cov_pair_3_8_N_N $cov_pair_3_8_N_CA $cov_pair_3_8_N_O $cov_pair_3_8_CA_N $cov_pair_3_8_CA_CA $cov_pair_3_8_CA_O $cov_pair_3_8_O_N $cov_pair_3_8_O_CA $cov_pair_3_8_O_O $cov_pair_3_9_N_N $cov_pair_3_9_N_CA $cov_pair_3_9_N_O $cov_pair_3_9_CA_N $cov_pair_3_9_CA_CA $cov_pair_3_9_CA_O $cov_pair_3_9_O_N $cov_pair_3_9_O_CA $cov_pair_3_9_O_O $cov_pair_3_10_N_N $cov_pair_3_10_N_CA $cov_pair_3_10_N_O $cov_pair_3_10_CA_N $cov_pair_3_10_CA_CA $cov_pair_3_10_CA_O $cov_pair_3_10_O_N $cov_pair_3_10_O_CA $cov_pair_3_10_O_O $cov_pair_4_5_N_N $cov_pair_4_5_N_CA $cov_pair_4_5_N_O $cov_pair_4_5_CA_N $cov_pair_4_5_CA_CA $cov_pair_4_5_CA_O $cov_pair_4_5_O_N $cov_pair_4_5_O_CA $cov_pair_4_5_O_O $cov_pair_4_6_N_N $cov_pair_4_6_N_CA $cov_pair_4_6_N_O $cov_pair_4_6_CA_N $cov_pair_4_6_CA_CA $cov_pair_4_6_CA_O $cov_pair_4_6_O_N $cov_pair_4_6_O_CA $cov_pair_4_6_O_O $cov_pair_4_7_N_N $cov_pair_4_7_N_CA $cov_pair_4_7_N_O $cov_pair_4_7_CA_N $cov_pair_4_7_CA_CA $cov_pair_4_7_CA_O $cov_pair_4_7_O_N $cov_pair_4_7_O_CA $cov_pair_4_7_O_O $cov_pair_4_8_N_N $cov_pair_4_8_N_CA $cov_pair_4_8_N_O $cov_pair_4_8_CA_N $cov_pair_4_8_CA_CA $cov_pair_4_8_CA_O $cov_pair_4_8_O_N $cov_pair_4_8_O_CA $cov_pair_4_8_O_O $cov_pair_4_9_N_N $cov_pair_4_9_N_CA $cov_pair_4_9_N_O $cov_pair_4_9_CA_N $cov_pair_4_9_CA_CA $cov_pair_4_9_CA_O $cov_pair_4_9_O_N $cov_pair_4_9_O_CA $cov_pair_4_9_O_O $cov_pair_4_10_N_N $cov_pair_4_10_N_CA $cov_pair_4_10_N_O $cov_pair_4_10_CA_N $cov_pair_4_10_CA_CA $cov_pair_4_10_CA_O $cov_pair_4_10_O_N $cov_pair_4_10_O_CA $cov_pair_4_10_O_O $cov_pair_5_6_N_N $cov_pair_5_6_N_CA $cov_pair_5_6_N_O $cov_pair_5_6_CA_N $cov_pair_5_6_CA_CA $cov_pair_5_6_CA_O $cov_pair_5_6_O_N $cov_pair_5_6_O_CA $cov_pair_5_6_O_O $cov_pair_5_7_N_N $cov_pair_5_7_N_CA $cov_pair_5_7_N_O $cov_pair_5_7_CA_N $cov_pair_5_7_CA_CA $cov_pair_5_7_CA_O $cov_pair_5_7_O_N $cov_pair_5_7_O_CA $cov_pair_5_7_O_O $cov_pair_5_8_N_N $cov_pair_5_8_N_CA $cov_pair_5_8_N_O $cov_pair_5_8_CA_N $cov_pair_5_8_CA_CA $cov_pair_5_8_CA_O $cov_pair_5_8_O_N $cov_pair_5_8_O_CA $cov_pair_5_8_O_O $cov_pair_5_9_N_N $cov_pair_5_9_N_CA $cov_pair_5_9_N_O $cov_pair_5_9_CA_N $cov_pair_5_9_CA_CA $cov_pair_5_9_CA_O $cov_pair_5_9_O_N $cov_pair_5_9_O_CA $cov_pair_5_9_O_O $cov_pair_5_10_N_N $cov_pair_5_10_N_CA $cov_pair_5_10_N_O $cov_pair_5_10_CA_N $cov_pair_5_10_CA_CA $cov_pair_5_10_CA_O $cov_pair_5_10_O_N $cov_pair_5_10_O_CA $cov_pair_5_10_O_O $cov_pair_6_7_N_N $cov_pair_6_7_N_CA $cov_pair_6_7_N_O $cov_pair_6_7_CA_N $cov_pair_6_7_CA_CA $cov_pair_6_7_CA_O $cov_pair_6_7_O_N $cov_pair_6_7_O_CA $cov_pair_6_7_O_O $cov_pair_6_8_N_N $cov_pair_6_8_N_CA $cov_pair_6_8_N_O $cov_pair_6_8_CA_N $cov_pair_6_8_CA_CA $cov_pair_6_8_CA_O $cov_pair_6_8_O_N $cov_pair_6_8_O_CA $cov_pair_6_8_O_O $cov_pair_6_9_N_N $cov_pair_6_9_N_CA $cov_pair_6_9_N_O $cov_pair_6_9_CA_N $cov_pair_6_9_CA_CA $cov_pair_6_9_CA_O $cov_pair_6_9_O_N $cov_pair_6_9_O_CA $cov_pair_6_9_O_O $cov_pair_6_10_N_N $cov_pair_6_10_N_CA $cov_pair_6_10_N_O $cov_pair_6_10_CA_N $cov_pair_6_10_CA_CA $cov_pair_6_10_CA_O $cov_pair_6_10_O_N $cov_pair_6_10_O_CA $cov_pair_6_10_O_O $cov_pair_7_8_N_N $cov_pair_7_8_N_CA $cov_pair_7_8_N_O $cov_pair_7_8_CA_N $cov_pair_7_8_CA_CA $cov_pair_7_8_CA_O $cov_pair_7_8_O_N $cov_pair_7_8_O_CA $cov_pair_7_8_O_O $cov_pair_7_9_N_N $cov_pair_7_9_N_CA $cov_pair_7_9_N_O $cov_pair_7_9_CA_N $cov_pair_7_9_CA_CA $cov_pair_7_9_CA_O $cov_pair_7_9_O_N $cov_pair_7_9_O_CA $cov_pair_7_9_O_O $cov_pair_7_10_N_N $cov_pair_7_10_N_CA $cov_pair_7_10_N_O $cov_pair_7_10_CA_N $cov_pair_7_10_CA_CA $cov_pair_7_10_CA_O $cov_pair_7_10_O_N $cov_pair_7_10_O_CA $cov_pair_7_10_O_O $cov_pair_8_9_N_N $cov_pair_8_9_N_CA $cov_pair_8_9_N_O $cov_pair_8_9_CA_N $cov_pair_8_9_CA_CA $cov_pair_8_9_CA_O $cov_pair_8_9_O_N $cov_pair_8_9_O_CA $cov_pair_8_9_O_O $cov_pair_8_10_N_N $cov_pair_8_10_N_CA $cov_pair_8_10_N_O $cov_pair_8_10_CA_N $cov_pair_8_10_CA_CA $cov_pair_8_10_CA_O $cov_pair_8_10_O_N $cov_pair_8_10_O_CA $cov_pair_8_10_O_O $cov_pair_9_10_N_N $cov_pair_9_10_N_CA $cov_pair_9_10_N_O $cov_pair_9_10_CA_N $cov_pair_9_10_CA_CA $cov_pair_9_10_CA_O $cov_pair_9_10_O_N $cov_pair_9_10_O_CA $cov_pair_9_10_O_O]
		set q_value [NC_forward $q_input]

        if {$qthis == 0} {
            if {$q_value > [lindex $qlist $qright]} {
                set t_final [expr $t/1000.0]
                print "final_result $qthis $qright $t_final $q_value"
                exit
            }
        } elseif {$qthis == [expr {$qlen - 1}]} {
            if {$q_value < [lindex $qlist $qleft]} {
                set t_final [expr $t/1000.0]
                print "final_result $qthis $qleft $t_final $q_value"
                exit
            }
        } else {
            if {$qleft == 0} {
                if {$cov_sum_h < $reactant_center} {
                    set t_final [expr $t/1000.0]
                    print "final_result $qthis $qleft $t_final $q_value"
                    exit
                }
            } else {
                if {$q_value < [lindex $qlist $qleft]} {
                    set t_final [expr $t/1000.0]
                    print "final_result $qthis $qleft $t_final $q_value"
                    exit
                }
            }
            if {$qright == [expr {$qlen - 1}]} {
                if {$cov_sum_h > $product_center} {
                    set t_final [expr $t/1000.0]
                    print "final_result $qthis $qright $t_final $q_value"
                    exit
                }
            } else {
                if {$q_value > [lindex $qlist $qright]} {
                    set t_final [expr $t/1000.0]
                    print "final_result $qthis $qright $t_final $q_value"
                    exit
                }
            }
        }
    }
}
