ColvarsTrajFrequency 1000
ColvarsRestartFrequency 1000

#scriptedColvarForces on

colvar {
    name hbond1
    distance {
        group1 {atomNumbers 1}     
        group2 {atomNumbers 165}  
    }
}

colvar {
    name hbond2
    distance {
        group1 {atomNumbers 23}     
        group2 {atomNumbers 145}  
    }
}

colvar {
    name hbond3
    distance {
        group1 {atomNumbers 45}     
        group2 {atomNumbers 120}  
    }
}

colvar {
    name hbond4
    distance {
        group1 {atomNumbers 56}     
        group2 {atomNumbers 107}  
    }
}

colvar {
    name dist_hbond
    customFunction hbond1+hbond2+hbond3+hbond4
    
    distance {
		name hbond1
        group1 {atomNumbers 1}     
        group2 {atomNumbers 165}  
    }
    
    distance {
		name hbond2
        group1 {atomNumbers 23}     
        group2 {atomNumbers 145}  
    }
    
    distance {
		name hbond3
        group1 {atomNumbers 45}     
        group2 {atomNumbers 120}  
    }
    
    distance {
		name hbond4
        group1 {atomNumbers 56}     
        group2 {atomNumbers 107}  
    }
}

harmonicWalls {
    name harmonicWall_dist_hbond
    colvars dist_hbond
    lowerWalls 16.1 
    upperWalls 16.9
    lowerWallConstant 10.0
    upperWallConstant 10.0

}    


